import type { ThemeConfig } from "antd";

export const modernTheme: ThemeConfig = {
  token: {
    colorPrimary: "#F0B90B",
    colorSuccess: "#0ECB81",
    colorWarning: "#F0B90B",
    colorError: "#F6465D",
    colorInfo: "#4D7EFF",
    fontFamily: `"Inter","SF Pro Display","PingFang SC","Hiragino Sans GB","Microsoft YaHei",sans-serif`,
    fontSize: 14,
    borderRadius: 10,
    borderRadiusLG: 12,
    borderRadiusSM: 8,
    boxShadow: "0 12px 28px rgba(0, 0, 0, 0.45)",
    boxShadowSecondary: "0 20px 48px rgba(0, 0, 0, 0.55)",
    padding: 16,
    margin: 16,
    colorBgContainer: "#181A20",
    colorBgElevated: "#1E2329",
    colorBgLayout: "#0B0E11",
    colorBorder: "#2B3139",
    colorBorderSecondary: "#1F242C",
    colorText: "#EAECEF",
    colorTextSecondary: "#B7BDC6",
    colorTextTertiary: "#848E9C",
    colorTextQuaternary: "#5E6673",
    colorLink: "#F0B90B",
    colorLinkHover: "#FCD535",
    colorLinkActive: "#D9A409",
  },
  components: {
    Button: {
      controlHeight: 40,
      controlHeightLG: 48,
      controlHeightSM: 32,
      fontWeight: 600,
      borderRadius: 10,
      primaryShadow: "0 10px 24px rgba(240, 185, 11, 0.28)",
      defaultBg: "#1E2329",
      defaultBorderColor: "#2B3139",
      defaultColor: "#EAECEF",
      primaryColor: "#0B0E11",
    },
    Input: {
      controlHeight: 40,
      controlHeightLG: 48,
      controlHeightSM: 32,
      paddingBlock: 10,
      paddingBlockLG: 12,
      paddingBlockSM: 8,
      activeBorderColor: "#F0B90B",
      hoverBorderColor: "#F0B90B",
      colorBgContainer: "#1E2329",
      colorText: "#EAECEF",
      colorTextPlaceholder: "#5E6673",
    },
    Select: {
      controlHeight: 40,
      controlHeightLG: 48,
      controlHeightSM: 32,
      colorBgContainer: "#1E2329",
      optionSelectedBg: "rgba(240, 185, 11, 0.12)",
      optionActiveBg: "rgba(240, 185, 11, 0.08)",
    },
    Card: {
      borderRadiusLG: 12,
      paddingLG: 24,
      colorBgContainer: "#181A20",
    },
    Modal: {
      borderRadiusLG: 14,
      contentBg: "#181A20",
      headerBg: "#181A20",
      titleColor: "#EAECEF",
    },
    Message: {
      contentBg: "#1E2329",
      contentPadding: "12px 16px",
    },
    Tag: {
      borderRadiusSM: 999,
    },
    Layout: {
      headerBg: "#0B0E11",
      headerHeight: 76,
      headerPadding: "0 24px",
      siderBg: "#0B0E11",
      bodyBg: "#0B0E11",
    },
    Table: {
      borderColor: "#2B3139",
      headerBg: "#14171D",
      headerColor: "#B7BDC6",
      rowHoverBg: "#1E2329",
      colorBgContainer: "#181A20",
    },
    Menu: {
      itemBg: "transparent",
      subMenuItemBg: "transparent",
      itemColor: "#B7BDC6",
      itemHoverColor: "#F0B90B",
      itemSelectedColor: "#F0B90B",
      itemSelectedBg: "rgba(240, 185, 11, 0.10)",
      itemActiveBg: "rgba(240, 185, 11, 0.06)",
    },
    Progress: {
      defaultColor: "#F0B90B",
    },
    Tabs: {
      itemSelectedColor: "#F0B90B",
      itemHoverColor: "#FCD535",
      inkBarColor: "#F0B90B",
    },
    Checkbox: {
      colorPrimary: "#F0B90B",
    },
    Switch: {
      colorPrimary: "#F0B90B",
    },
    Pagination: {
      colorPrimary: "#F0B90B",
    },
  },
};

export const whatsappTheme: ThemeConfig = {
  token: {
    colorPrimary: "#25D366",
    colorSuccess: "#25D366",
    colorBgContainer: "#FFFFFF",
    colorBgLayout: "#F0F2F5",
    borderRadius: 8,
    fontFamily: `"IBM Plex Sans","PingFang SC","Hiragino Sans GB","Microsoft YaHei","Segoe UI",sans-serif`,
  },
  components: {
    Layout: {
      headerBg: "#FFFFFF",
      siderBg: "#FFFFFF",
      bodyBg: "#F0F2F5",
    },
  },
};
