-- Coin platform / coin user / coin / trade domain tables.
-- Source: server/service/*/repository/model.go

CREATE TABLE IF NOT EXISTS `coin_platform` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `code` varchar(32) DEFAULT NULL COMMENT '平台代码 binance/okx/huobi',
  `name` varchar(64) DEFAULT NULL COMMENT '平台名称',
  `full_name` varchar(128) DEFAULT NULL COMMENT '平台全称',
  `icon` varchar(255) DEFAULT NULL COMMENT '平台图标',
  `website` varchar(255) DEFAULT NULL COMMENT '官网地址',
  `country` varchar(64) DEFAULT NULL COMMENT '所在国家',
  `api_base_url` varchar(255) DEFAULT NULL COMMENT 'API 基础地址',
  `ws_base_url` varchar(255) DEFAULT NULL COMMENT 'WebSocket 基础地址',
  `docs_url` varchar(255) DEFAULT NULL COMMENT '接入文档地址',
  `supported_types` varchar(255) DEFAULT NULL COMMENT '支持的业务类型 spot,futures,margin',
  `default_fee_rate` decimal(10,6) DEFAULT 0 COMMENT '默认手续费率',
  `rate_limit_per_sec` int unsigned DEFAULT 0 COMMENT '每秒限频',
  `status` varchar(32) DEFAULT NULL COMMENT '状态 online/offline/maintenance',
  `sort_order` int DEFAULT 0 COMMENT '排序',
  `description` varchar(500) DEFAULT NULL COMMENT '描述',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_code` (`code`),
  KEY `idx_name` (`name`),
  KEY `idx_country` (`country`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='币平台';

CREATE TABLE IF NOT EXISTS `coin_platform_coin` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `platform_id` bigint unsigned DEFAULT NULL COMMENT '平台ID',
  `platform_code` varchar(32) DEFAULT NULL COMMENT '平台代码',
  `coin_id` bigint unsigned DEFAULT NULL COMMENT '币种ID',
  `coin_code` varchar(32) DEFAULT NULL COMMENT '币种代码',
  `platform_symbol` varchar(64) DEFAULT NULL COMMENT '平台侧符号',
  `chain_name` varchar(32) DEFAULT NULL COMMENT '主链',
  `contract_address` varchar(128) DEFAULT NULL COMMENT '合约地址',
  `deposit_enable` tinyint unsigned DEFAULT 1 COMMENT '是否可充值',
  `withdraw_enable` tinyint unsigned DEFAULT 1 COMMENT '是否可提现',
  `trade_enable` tinyint unsigned DEFAULT 1 COMMENT '是否可交易',
  `min_withdrawal` decimal(36,18) DEFAULT 0 COMMENT '最小提现额',
  `withdrawal_fee` decimal(36,18) DEFAULT 0 COMMENT '提现手续费',
  `confirmations` int unsigned DEFAULT 0 COMMENT '充值所需确认数',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_platform_coin` (`platform_id`, `coin_id`),
  KEY `idx_platform_code` (`platform_code`),
  KEY `idx_coin_code` (`coin_code`),
  KEY `idx_chain_name` (`chain_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='平台币种';

CREATE TABLE IF NOT EXISTS `coin_platform_account` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `platform_id` bigint unsigned DEFAULT NULL COMMENT '平台ID',
  `platform_code` varchar(32) DEFAULT NULL COMMENT '平台代码',
  `account_name` varchar(64) DEFAULT NULL COMMENT '账户名称/标签',
  `account_type` varchar(32) DEFAULT NULL COMMENT '账户类型 master/sub/read_only',
  `api_key` varchar(255) DEFAULT NULL COMMENT 'API Key',
  `api_secret` varchar(512) DEFAULT NULL COMMENT 'API Secret(加密存储)',
  `passphrase` varchar(255) DEFAULT NULL COMMENT 'OKX 等需要的口令',
  `ip_whitelist` varchar(500) DEFAULT NULL COMMENT 'IP白名单 逗号分隔',
  `permissions` varchar(255) DEFAULT NULL COMMENT '权限 read/trade/withdraw',
  `status` varchar(32) DEFAULT NULL COMMENT '状态 active/disabled/expired',
  `last_used_time` datetime DEFAULT NULL COMMENT '最近使用时间',
  `expire_time` datetime DEFAULT NULL COMMENT '过期时间',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_platform_id` (`platform_id`),
  KEY `idx_platform_code` (`platform_code`),
  KEY `idx_account_name` (`account_name`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='平台账户';

CREATE TABLE IF NOT EXISTS `coin` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `code` varchar(32) DEFAULT NULL COMMENT '币种代码 BTC/ETH/USDT',
  `name` varchar(64) DEFAULT NULL COMMENT '币种名称',
  `full_name` varchar(128) DEFAULT NULL COMMENT '币种全称',
  `icon` varchar(255) DEFAULT NULL COMMENT '图标URL',
  `chain_name` varchar(32) DEFAULT NULL COMMENT '主链名称 BTC/ETH/TRC20',
  `contract_address` varchar(128) DEFAULT NULL COMMENT '合约地址',
  `decimals` tinyint unsigned DEFAULT 8 COMMENT '小数位精度',
  `price_precision` tinyint unsigned DEFAULT 8 COMMENT '价格精度',
  `amount_precision` tinyint unsigned DEFAULT 8 COMMENT '数量精度',
  `min_withdrawal` decimal(36,18) DEFAULT 0 COMMENT '最小提现额度',
  `max_withdrawal` decimal(36,18) DEFAULT 0 COMMENT '最大提现额度',
  `withdrawal_fee` decimal(36,18) DEFAULT 0 COMMENT '提现手续费',
  `deposit_enable` tinyint unsigned DEFAULT 1 COMMENT '是否允许充值',
  `withdraw_enable` tinyint unsigned DEFAULT 1 COMMENT '是否允许提现',
  `trade_enable` tinyint unsigned DEFAULT 1 COMMENT '是否允许交易',
  `status` varchar(32) DEFAULT NULL COMMENT '状态: online/offline/maintenance',
  `sort_order` int DEFAULT 0 COMMENT '排序',
  `description` varchar(500) DEFAULT NULL COMMENT '描述',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_code` (`code`),
  KEY `idx_name` (`name`),
  KEY `idx_chain_name` (`chain_name`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='币种';

CREATE TABLE IF NOT EXISTS `coin_pair` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `symbol` varchar(32) DEFAULT NULL COMMENT '交易对符号 BTC-USDT',
  `base_coin_id` bigint unsigned DEFAULT NULL COMMENT '基础币种ID',
  `base_coin_code` varchar(32) DEFAULT NULL COMMENT '基础币种代码',
  `quote_coin_id` bigint unsigned DEFAULT NULL COMMENT '计价币种ID',
  `quote_coin_code` varchar(32) DEFAULT NULL COMMENT '计价币种代码',
  `price_precision` tinyint unsigned DEFAULT 8 COMMENT '价格精度',
  `amount_precision` tinyint unsigned DEFAULT 8 COMMENT '数量精度',
  `min_amount` decimal(36,18) DEFAULT 0 COMMENT '最小下单量',
  `max_amount` decimal(36,18) DEFAULT 0 COMMENT '最大下单量',
  `min_total` decimal(36,18) DEFAULT 0 COMMENT '最小成交额',
  `taker_fee_rate` decimal(10,6) DEFAULT 0 COMMENT '吃单手续费率',
  `maker_fee_rate` decimal(10,6) DEFAULT 0 COMMENT '挂单手续费率',
  `status` varchar(32) DEFAULT NULL COMMENT '状态: online/offline/halt',
  `sort_order` int DEFAULT 0 COMMENT '排序',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_symbol` (`symbol`),
  KEY `idx_base_coin_id` (`base_coin_id`),
  KEY `idx_base_coin_code` (`base_coin_code`),
  KEY `idx_quote_coin_id` (`quote_coin_id`),
  KEY `idx_quote_coin_code` (`quote_coin_code`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='币种交易对';

CREATE TABLE IF NOT EXISTS `coin_price` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `coin_id` bigint unsigned DEFAULT NULL COMMENT '币种ID',
  `coin_code` varchar(32) DEFAULT NULL COMMENT '币种代码',
  `quote_code` varchar(32) DEFAULT NULL COMMENT '计价币种代码',
  `price` decimal(36,18) DEFAULT 0 COMMENT '最新价格',
  `change_24h` decimal(10,6) DEFAULT 0 COMMENT '24小时涨跌幅',
  `volume_24h` decimal(36,18) DEFAULT 0 COMMENT '24小时成交量',
  `high_24h` decimal(36,18) DEFAULT 0 COMMENT '24小时最高价',
  `low_24h` decimal(36,18) DEFAULT 0 COMMENT '24小时最低价',
  `source` varchar(32) DEFAULT NULL COMMENT '价格来源 binance/okx',
  PRIMARY KEY (`id`),
  KEY `idx_coin_id` (`coin_id`),
  KEY `idx_coin_code` (`coin_code`),
  KEY `idx_quote_code` (`quote_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='币价';

CREATE TABLE IF NOT EXISTS `coin_user` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `platform_id` bigint unsigned DEFAULT 0 COMMENT '所属平台ID',
  `platform_code` varchar(32) DEFAULT NULL COMMENT '所属平台代码',
  `account` varchar(128) DEFAULT NULL COMMENT '账号(平台账户标识)',
  `username` varchar(64) DEFAULT NULL COMMENT '用户名',
  `nickname` varchar(64) DEFAULT NULL COMMENT '昵称',
  `email` varchar(128) DEFAULT NULL COMMENT '邮箱',
  `phone` varchar(32) DEFAULT NULL COMMENT '手机号',
  `password` varchar(128) DEFAULT NULL COMMENT '密码',
  `secret_key` varchar(512) DEFAULT NULL COMMENT '秘钥(加密存储)',
  `balance` decimal(36,18) DEFAULT 0 COMMENT '账户总余额(USDT)',
  `country` varchar(32) DEFAULT NULL COMMENT '国家',
  `kyc_level` tinyint unsigned DEFAULT 0 COMMENT 'KYC等级(0未认证 1初级 2高级)',
  `kyc_status` varchar(32) DEFAULT NULL COMMENT 'KYC状态: pending/approved/rejected',
  `status` varchar(32) DEFAULT NULL COMMENT '账户状态: active/locked/frozen',
  `invite_code` varchar(32) DEFAULT NULL COMMENT '邀请码',
  `inviter_id` bigint unsigned DEFAULT 0 COMMENT '邀请人ID',
  `last_login_ip` varchar(64) DEFAULT NULL COMMENT '最后登录IP',
  `last_login_time` datetime DEFAULT NULL COMMENT '最后登录时间',
  `google_auth_key` varchar(64) DEFAULT NULL COMMENT '谷歌验证密钥',
  `two_fa_enabled` tinyint unsigned DEFAULT 0 COMMENT '是否开启二次验证',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_username` (`username`),
  UNIQUE KEY `idx_invite_code` (`invite_code`),
  KEY `idx_platform_id` (`platform_id`),
  KEY `idx_platform_code` (`platform_code`),
  KEY `idx_account` (`account`),
  KEY `idx_email` (`email`),
  KEY `idx_phone` (`phone`),
  KEY `idx_kyc_status` (`kyc_status`),
  KEY `idx_status` (`status`),
  KEY `idx_inviter_id` (`inviter_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='币用户';

CREATE TABLE IF NOT EXISTS `coin_user_asset` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `user_id` bigint unsigned DEFAULT NULL COMMENT '用户ID',
  `coin_id` bigint unsigned DEFAULT NULL COMMENT '币种ID',
  `coin_code` varchar(32) DEFAULT NULL COMMENT '币种代码',
  `available` decimal(36,18) DEFAULT 0 COMMENT '可用余额',
  `frozen` decimal(36,18) DEFAULT 0 COMMENT '冻结余额',
  `total` decimal(36,18) DEFAULT 0 COMMENT '总余额',
  `address` varchar(128) DEFAULT NULL COMMENT '充值地址',
  `withdraw_enable` tinyint unsigned DEFAULT 1 COMMENT '是否允许提现',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_user_coin` (`user_id`, `coin_id`),
  KEY `idx_coin_code` (`coin_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='币用户资产';

CREATE TABLE IF NOT EXISTS `coin_user_login_record` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `user_id` bigint unsigned DEFAULT NULL COMMENT '用户ID',
  `ip` varchar(64) DEFAULT NULL COMMENT '登录IP',
  `device` varchar(128) DEFAULT NULL COMMENT '设备信息',
  `location` varchar(128) DEFAULT NULL COMMENT '位置',
  `success` tinyint unsigned DEFAULT 1 COMMENT '是否成功',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='币用户登录记录';

CREATE TABLE IF NOT EXISTS `coin_user_position` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `user_id` bigint unsigned DEFAULT NULL COMMENT '用户ID',
  `symbol` varchar(32) DEFAULT NULL COMMENT '交易对 BTC-USDT',
  `base_coin_code` varchar(32) DEFAULT NULL COMMENT '基础币种',
  `quote_coin_code` varchar(32) DEFAULT NULL COMMENT '计价币种',
  `amount` decimal(36,18) DEFAULT 0 COMMENT '持仓数量',
  `avg_cost_price` decimal(36,18) DEFAULT 0 COMMENT '平均成本价',
  `total_cost` decimal(36,18) DEFAULT 0 COMMENT '持仓总成本',
  `status` varchar(16) DEFAULT 'open' COMMENT '状态 open/closed',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_user_symbol` (`user_id`, `symbol`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_symbol` (`symbol`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='币用户持仓';

CREATE TABLE IF NOT EXISTS `coin_user_position_analysis` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `user_id` bigint unsigned DEFAULT NULL COMMENT '用户ID',
  `position_id` bigint unsigned DEFAULT 0 COMMENT '关联仓位ID',
  `symbol` varchar(32) DEFAULT NULL COMMENT '币种/交易对 BTC-USDT',
  `side` varchar(8) DEFAULT NULL COMMENT '开仓方向 long/short',
  `avg_price` decimal(36,18) DEFAULT 0 COMMENT '仓位平均价格',
  `liquidation_price` decimal(36,18) DEFAULT 0 COMMENT '爆仓价格',
  `leverage` decimal(10,2) DEFAULT 1 COMMENT '开仓倍数',
  `contracts` decimal(36,18) DEFAULT 0 COMMENT '开仓张数',
  `margin` decimal(36,18) DEFAULT 0 COMMENT '保证金',
  `balance_at_open` decimal(36,18) DEFAULT 0 COMMENT '开仓时用户余额',
  `ai_advice` text COMMENT 'AI建议',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_position_id` (`position_id`),
  KEY `idx_symbol` (`symbol`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='币用户持仓分析';

CREATE TABLE IF NOT EXISTS `trade_order` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `platform_id` bigint unsigned DEFAULT 0 COMMENT '所属平台ID',
  `platform_code` varchar(32) DEFAULT NULL COMMENT '所属平台代码',
  `trade_category` varchar(32) DEFAULT NULL COMMENT '交易类别 spot/futures/margin',
  `trade_type` varchar(16) DEFAULT NULL COMMENT '交易类型 simulation/real',
  `order_no` varchar(64) DEFAULT NULL COMMENT '订单号',
  `user_id` bigint unsigned DEFAULT NULL COMMENT '用户ID',
  `symbol` varchar(32) DEFAULT NULL COMMENT '交易对 BTC-USDT',
  `base_coin_code` varchar(32) DEFAULT NULL COMMENT '基础币种',
  `quote_coin_code` varchar(32) DEFAULT NULL COMMENT '计价币种',
  `side` varchar(8) DEFAULT NULL COMMENT '方向 buy/sell',
  `order_type` varchar(16) DEFAULT NULL COMMENT '类型 limit/market/stop_limit',
  `price` decimal(36,18) DEFAULT 0 COMMENT '委托价格',
  `amount` decimal(36,18) DEFAULT 0 COMMENT '委托数量',
  `total` decimal(36,18) DEFAULT 0 COMMENT '委托总额',
  `stop_price` decimal(36,18) DEFAULT 0 COMMENT '触发价',
  `filled_amount` decimal(36,18) DEFAULT 0 COMMENT '已成交数量',
  `filled_total` decimal(36,18) DEFAULT 0 COMMENT '已成交总额',
  `avg_filled_price` decimal(36,18) DEFAULT 0 COMMENT '平均成交价',
  `fee_coin_code` varchar(32) DEFAULT NULL COMMENT '手续费币种',
  `fee_amount` decimal(36,18) DEFAULT 0 COMMENT '手续费',
  `status` varchar(32) DEFAULT NULL COMMENT '状态 pending/partial/filled/canceled/rejected',
  `time_in_force` varchar(8) DEFAULT 'GTC' COMMENT 'GTC/IOC/FOK',
  `source` varchar(32) DEFAULT NULL COMMENT '下单来源 web/app/api',
  `client_order_id` varchar(64) DEFAULT NULL COMMENT '客户端自定义订单ID',
  `submitted_time` datetime DEFAULT NULL COMMENT '提交时间',
  `finished_time` datetime DEFAULT NULL COMMENT '完结时间',
  `cancel_reason` varchar(255) DEFAULT NULL COMMENT '取消原因',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_order_no` (`order_no`),
  KEY `idx_platform_id` (`platform_id`),
  KEY `idx_platform_code` (`platform_code`),
  KEY `idx_trade_category` (`trade_category`),
  KEY `idx_trade_type` (`trade_type`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_symbol` (`symbol`),
  KEY `idx_side` (`side`),
  KEY `idx_order_type` (`order_type`),
  KEY `idx_status` (`status`),
  KEY `idx_client_order_id` (`client_order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='交易订单';

CREATE TABLE IF NOT EXISTS `trade_match` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `platform_id` bigint unsigned DEFAULT 0 COMMENT '所属平台ID',
  `platform_code` varchar(32) DEFAULT NULL COMMENT '所属平台代码',
  `trade_no` varchar(64) DEFAULT NULL COMMENT '成交单号',
  `symbol` varchar(32) DEFAULT NULL COMMENT '交易对',
  `taker_order_no` varchar(64) DEFAULT NULL COMMENT '吃单订单号',
  `maker_order_no` varchar(64) DEFAULT NULL COMMENT '挂单订单号',
  `taker_user_id` bigint unsigned DEFAULT NULL COMMENT '吃单用户ID',
  `maker_user_id` bigint unsigned DEFAULT NULL COMMENT '挂单用户ID',
  `side` varchar(8) DEFAULT NULL COMMENT '吃单方向 buy/sell',
  `price` decimal(36,18) DEFAULT 0 COMMENT '成交价',
  `amount` decimal(36,18) DEFAULT 0 COMMENT '成交数量',
  `total` decimal(36,18) DEFAULT 0 COMMENT '成交金额',
  `taker_fee` decimal(36,18) DEFAULT 0 COMMENT '吃单手续费',
  `maker_fee` decimal(36,18) DEFAULT 0 COMMENT '挂单手续费',
  `matched_time` datetime DEFAULT NULL COMMENT '撮合时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_trade_no` (`trade_no`),
  KEY `idx_platform_id` (`platform_id`),
  KEY `idx_platform_code` (`platform_code`),
  KEY `idx_symbol` (`symbol`),
  KEY `idx_taker_order_no` (`taker_order_no`),
  KEY `idx_maker_order_no` (`maker_order_no`),
  KEY `idx_taker_user_id` (`taker_user_id`),
  KEY `idx_maker_user_id` (`maker_user_id`),
  KEY `idx_matched_time` (`matched_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='交易成交';

CREATE TABLE IF NOT EXISTS `trade_kline` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `symbol` varchar(32) DEFAULT NULL COMMENT '交易对',
  `interval` varchar(8) DEFAULT NULL COMMENT '周期 1m/5m/15m/1h/4h/1d',
  `open_time` datetime DEFAULT NULL COMMENT '开始时间',
  `close_time` datetime DEFAULT NULL COMMENT '结束时间',
  `open_price` decimal(36,18) DEFAULT 0 COMMENT '开盘价',
  `high_price` decimal(36,18) DEFAULT 0 COMMENT '最高价',
  `low_price` decimal(36,18) DEFAULT 0 COMMENT '最低价',
  `close_price` decimal(36,18) DEFAULT 0 COMMENT '收盘价',
  `volume` decimal(36,18) DEFAULT 0 COMMENT '成交量',
  `turnover` decimal(36,18) DEFAULT 0 COMMENT '成交额',
  `trade_count` bigint unsigned DEFAULT 0 COMMENT '成交笔数',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_symbol_interval_open` (`symbol`, `interval`, `open_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='交易K线';

CREATE TABLE IF NOT EXISTS `trade_detail` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `platform_id` bigint unsigned DEFAULT 0 COMMENT '平台ID',
  `platform_code` varchar(32) DEFAULT NULL COMMENT '平台代码',
  `trade_category` varchar(32) DEFAULT NULL COMMENT '交易类别 spot/futures/margin',
  `trade_type` varchar(16) DEFAULT NULL COMMENT '交易类型 simulation/real',
  `user_id` bigint unsigned DEFAULT NULL COMMENT '用户ID',
  `order_no` varchar(64) DEFAULT NULL COMMENT '关联订单号',
  `trade_no` varchar(64) DEFAULT NULL COMMENT '成交单号',
  `symbol` varchar(32) DEFAULT NULL COMMENT '交易对',
  `coin_code` varchar(32) DEFAULT NULL COMMENT '基础币种',
  `side` varchar(8) DEFAULT NULL COMMENT '成交方向 buy/sell',
  `open_direction` varchar(8) DEFAULT NULL COMMENT '开仓方向 long/short',
  `avg_open_price` decimal(36,18) DEFAULT 0 COMMENT '开仓平均价格',
  `liquidation_price` decimal(36,18) DEFAULT 0 COMMENT '爆仓价格',
  `leverage` decimal(10,2) DEFAULT 1 COMMENT '开仓倍数(杠杆)',
  `margin` decimal(36,18) DEFAULT 0 COMMENT '保证金',
  `user_balance_open` decimal(36,18) DEFAULT 0 COMMENT '开仓时用户余额',
  `price` decimal(36,18) DEFAULT 0 COMMENT '成交价',
  `amount` decimal(36,18) DEFAULT 0 COMMENT '成交数量',
  `total` decimal(36,18) DEFAULT 0 COMMENT '成交金额',
  `fee` decimal(36,18) DEFAULT 0 COMMENT '手续费',
  `pnl` decimal(36,18) DEFAULT 0 COMMENT '盈亏金额',
  `pnl_rate` decimal(18,8) DEFAULT 0 COMMENT '盈亏比率',
  `trade_time` datetime DEFAULT NULL COMMENT '成交时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_trade_no` (`trade_no`),
  KEY `idx_platform_id` (`platform_id`),
  KEY `idx_platform_code` (`platform_code`),
  KEY `idx_trade_category` (`trade_category`),
  KEY `idx_trade_type` (`trade_type`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_order_no` (`order_no`),
  KEY `idx_symbol` (`symbol`),
  KEY `idx_coin_code` (`coin_code`),
  KEY `idx_open_direction` (`open_direction`),
  KEY `idx_trade_time` (`trade_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='交易明细盈亏';

CREATE TABLE IF NOT EXISTS `trade_user_summary` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `user_id` bigint unsigned DEFAULT NULL COMMENT '用户ID',
  `platform_id` bigint unsigned DEFAULT NULL COMMENT '平台ID',
  `platform_code` varchar(32) DEFAULT NULL COMMENT '平台代码',
  `coin_code` varchar(32) DEFAULT NULL COMMENT '币种代码',
  `trade_category` varchar(32) DEFAULT NULL COMMENT '交易类别',
  `trade_date` varchar(10) DEFAULT NULL COMMENT '交易日期 yyyy-MM-dd',
  `total_orders` bigint DEFAULT 0 COMMENT '总订单数',
  `buy_orders` bigint DEFAULT 0 COMMENT '买入订单数',
  `sell_orders` bigint DEFAULT 0 COMMENT '卖出订单数',
  `buy_amount` decimal(36,18) DEFAULT 0 COMMENT '买入数量',
  `sell_amount` decimal(36,18) DEFAULT 0 COMMENT '卖出数量',
  `buy_total` decimal(36,18) DEFAULT 0 COMMENT '买入金额',
  `sell_total` decimal(36,18) DEFAULT 0 COMMENT '卖出金额',
  `total_fee` decimal(36,18) DEFAULT 0 COMMENT '总手续费',
  `total_volume` decimal(36,18) DEFAULT 0 COMMENT '总成交额',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_summary_dim` (`user_id`, `platform_id`, `coin_code`, `trade_category`, `trade_date`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_trade_date` (`trade_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户交易汇总';

CREATE TABLE IF NOT EXISTS `trade_user_pnl` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `user_id` bigint unsigned DEFAULT NULL COMMENT '用户ID',
  `platform_id` bigint unsigned DEFAULT NULL COMMENT '平台ID',
  `platform_code` varchar(32) DEFAULT NULL COMMENT '平台代码',
  `coin_code` varchar(32) DEFAULT NULL COMMENT '币种代码',
  `trade_category` varchar(32) DEFAULT NULL COMMENT '交易类别',
  `trade_date` varchar(10) DEFAULT NULL COMMENT '交易日期 yyyy-MM-dd',
  `realized_pnl` decimal(36,18) DEFAULT 0 COMMENT '已实现盈亏',
  `unrealized_pnl` decimal(36,18) DEFAULT 0 COMMENT '未实现盈亏',
  `total_pnl` decimal(36,18) DEFAULT 0 COMMENT '总盈亏',
  `pnl_rate` decimal(18,8) DEFAULT 0 COMMENT '盈亏比率',
  `position_amount` decimal(36,18) DEFAULT 0 COMMENT '持仓数量',
  `position_cost` decimal(36,18) DEFAULT 0 COMMENT '持仓成本',
  `position_value` decimal(36,18) DEFAULT 0 COMMENT '持仓市值',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_pnl_dim` (`user_id`, `platform_id`, `coin_code`, `trade_category`, `trade_date`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_trade_date` (`trade_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户交易盈亏';
