-- Coin platform / coin user / coin / trade domain tables.
-- Source: server/service/*/repository/model.go

CREATE TABLE IF NOT EXISTS `coin_platform` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `code` varchar(32) DEFAULT NULL COMMENT '平台代码 binance/okx/huobi',
  `name` varchar(64) DEFAULT NULL COMMENT '平台名称',
  `full_name` varchar(128) DEFAULT NULL COMMENT '平台全称',
  `icon` varchar(255) DEFAULT NULL COMMENT '平台图标',
  `website` varchar(255) DEFAULT NULL COMMENT '官网地址',
  `country` varchar(64) DEFAULT NULL COMMENT '所在国家',
  `api_base_url` varchar(255) DEFAULT NULL COMMENT 'API 基础地址',
  `ws_base_url` varchar(255) DEFAULT NULL COMMENT 'WebSocket 基础地址',
  `docs_url` varchar(255) DEFAULT NULL COMMENT '接入文档地址',
  `supported_types` varchar(255) DEFAULT NULL COMMENT '支持的业务类型 spot,futures,margin',
  `default_fee_rate` decimal(10,6) DEFAULT 0 COMMENT '默认手续费率',
  `rate_limit_per_sec` int unsigned DEFAULT 0 COMMENT '每秒限频',
  `status` varchar(32) DEFAULT NULL COMMENT '状态 online/offline/maintenance',
  `sort_order` int DEFAULT 0 COMMENT '排序',
  `description` varchar(500) DEFAULT NULL COMMENT '描述',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_code` (`code`),
  KEY `idx_name` (`name`),
  KEY `idx_country` (`country`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='币平台';

CREATE TABLE IF NOT EXISTS `coin_platform_coin` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `platform_id` bigint unsigned DEFAULT NULL COMMENT '平台ID',
  `platform_code` varchar(32) DEFAULT NULL COMMENT '平台代码',
  `coin_id` bigint unsigned DEFAULT NULL COMMENT '币种ID',
  `coin_code` varchar(32) DEFAULT NULL COMMENT '币种代码',
  `platform_symbol` varchar(64) DEFAULT NULL COMMENT '平台侧符号',
  `chain_name` varchar(32) DEFAULT NULL COMMENT '主链',
  `contract_address` varchar(128) DEFAULT NULL COMMENT '合约地址',
  `deposit_enable` tinyint unsigned DEFAULT 1 COMMENT '是否可充值',
  `withdraw_enable` tinyint unsigned DEFAULT 1 COMMENT '是否可提现',
  `trade_enable` tinyint unsigned DEFAULT 1 COMMENT '是否可交易',
  `min_withdrawal` decimal(36,18) DEFAULT 0 COMMENT '最小提现额',
  `withdrawal_fee` decimal(36,18) DEFAULT 0 COMMENT '提现手续费',
  `confirmations` int unsigned DEFAULT 0 COMMENT '充值所需确认数',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_platform_coin` (`platform_id`, `coin_id`),
  KEY `idx_platform_code` (`platform_code`),
  KEY `idx_coin_code` (`coin_code`),
  KEY `idx_chain_name` (`chain_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='平台币种';

CREATE TABLE IF NOT EXISTS `coin_platform_account` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `platform_id` bigint unsigned DEFAULT NULL COMMENT '平台ID',
  `platform_code` varchar(32) DEFAULT NULL COMMENT '平台代码',
  `account_name` varchar(64) DEFAULT NULL COMMENT '账户名称/标签',
  `account_type` varchar(32) DEFAULT NULL COMMENT '账户类型 master/sub/read_only',
  `api_key` varchar(255) DEFAULT NULL COMMENT 'API Key',
  `api_secret` varchar(512) DEFAULT NULL COMMENT 'API Secret(加密存储)',
  `passphrase` varchar(255) DEFAULT NULL COMMENT 'OKX 等需要的口令',
  `ip_whitelist` varchar(500) DEFAULT NULL COMMENT 'IP白名单 逗号分隔',
  `permissions` varchar(255) DEFAULT NULL COMMENT '权限 read/trade/withdraw',
  `status` varchar(32) DEFAULT NULL COMMENT '状态 active/disabled/expired',
  `last_used_time` datetime DEFAULT NULL COMMENT '最近使用时间',
  `expire_time` datetime DEFAULT NULL COMMENT '过期时间',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_platform_id` (`platform_id`),
  KEY `idx_platform_code` (`platform_code`),
  KEY `idx_account_name` (`account_name`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='平台账户';

CREATE TABLE IF NOT EXISTS `coin` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `code` varchar(32) DEFAULT NULL COMMENT '币种代码 BTC/ETH/USDT',
  `name` varchar(64) DEFAULT NULL COMMENT '币种名称',
  `full_name` varchar(128) DEFAULT NULL COMMENT '币种全称',
  `icon` varchar(255) DEFAULT NULL COMMENT '图标URL',
  `chain_name` varchar(32) DEFAULT NULL COMMENT '主链名称 BTC/ETH/TRC20',
  `contract_address` varchar(128) DEFAULT NULL COMMENT '合约地址',
  `decimals` tinyint unsigned DEFAULT 8 COMMENT '小数位精度',
  `price_precision` tinyint unsigned DEFAULT 8 COMMENT '价格精度',
  `amount_precision` tinyint unsigned DEFAULT 8 COMMENT '数量精度',
  `min_withdrawal` decimal(36,18) DEFAULT 0 COMMENT '最小提现额度',
  `max_withdrawal` decimal(36,18) DEFAULT 0 COMMENT '最大提现额度',
  `withdrawal_fee` decimal(36,18) DEFAULT 0 COMMENT '提现手续费',
  `deposit_enable` tinyint unsigned DEFAULT 1 COMMENT '是否允许充值',
  `withdraw_enable` tinyint unsigned DEFAULT 1 COMMENT '是否允许提现',
  `trade_enable` tinyint unsigned DEFAULT 1 COMMENT '是否允许交易',
  `status` varchar(32) DEFAULT NULL COMMENT '状态: online/offline/maintenance',
  `sort_order` int DEFAULT 0 COMMENT '排序',
  `description` varchar(500) DEFAULT NULL COMMENT '描述',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_code` (`code`),
  KEY `idx_name` (`name`),
  KEY `idx_chain_name` (`chain_name`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='币种';

CREATE TABLE IF NOT EXISTS `coin_pair` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `symbol` varchar(32) DEFAULT NULL COMMENT '交易对符号 BTC-USDT',
  `base_coin_id` bigint unsigned DEFAULT NULL COMMENT '基础币种ID',
  `base_coin_code` varchar(32) DEFAULT NULL COMMENT '基础币种代码',
  `quote_coin_id` bigint unsigned DEFAULT NULL COMMENT '计价币种ID',
  `quote_coin_code` varchar(32) DEFAULT NULL COMMENT '计价币种代码',
  `price_precision` tinyint unsigned DEFAULT 8 COMMENT '价格精度',
  `amount_precision` tinyint unsigned DEFAULT 8 COMMENT '数量精度',
  `min_amount` decimal(36,18) DEFAULT 0 COMMENT '最小下单量',
  `max_amount` decimal(36,18) DEFAULT 0 COMMENT '最大下单量',
  `min_total` decimal(36,18) DEFAULT 0 COMMENT '最小成交额',
  `taker_fee_rate` decimal(10,6) DEFAULT 0 COMMENT '吃单手续费率',
  `maker_fee_rate` decimal(10,6) DEFAULT 0 COMMENT '挂单手续费率',
  `status` varchar(32) DEFAULT NULL COMMENT '状态: online/offline/halt',
  `sort_order` int DEFAULT 0 COMMENT '排序',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_symbol` (`symbol`),
  KEY `idx_base_coin_id` (`base_coin_id`),
  KEY `idx_base_coin_code` (`base_coin_code`),
  KEY `idx_quote_coin_id` (`quote_coin_id`),
  KEY `idx_quote_coin_code` (`quote_coin_code`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='币种交易对';

CREATE TABLE IF NOT EXISTS `coin_price` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `coin_id` bigint unsigned DEFAULT NULL COMMENT '币种ID',
  `coin_code` varchar(32) DEFAULT NULL COMMENT '币种代码',
  `quote_code` varchar(32) DEFAULT NULL COMMENT '计价币种代码',
  `price` decimal(36,18) DEFAULT 0 COMMENT '最新价格',
  `change_24h` decimal(10,6) DEFAULT 0 COMMENT '24小时涨跌幅',
  `volume_24h` decimal(36,18) DEFAULT 0 COMMENT '24小时成交量',
  `high_24h` decimal(36,18) DEFAULT 0 COMMENT '24小时最高价',
  `low_24h` decimal(36,18) DEFAULT 0 COMMENT '24小时最低价',
  `source` varchar(32) DEFAULT NULL COMMENT '价格来源 binance/okx',
  PRIMARY KEY (`id`),
  KEY `idx_coin_id` (`coin_id`),
  KEY `idx_coin_code` (`coin_code`),
  KEY `idx_quote_code` (`quote_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='币价';

CREATE TABLE IF NOT EXISTS `coin_user` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `platform_id` bigint unsigned DEFAULT 0 COMMENT '所属平台ID',
  `platform_code` varchar(32) DEFAULT NULL COMMENT '所属平台代码',
  `account` varchar(128) DEFAULT NULL COMMENT '账号(平台账户标识)',
  `username` varchar(64) DEFAULT NULL COMMENT '用户名',
  `nickname` varchar(64) DEFAULT NULL COMMENT '昵称',
  `email` varchar(128) DEFAULT NULL COMMENT '邮箱',
  `phone` varchar(32) DEFAULT NULL COMMENT '手机号',
  `password` varchar(128) DEFAULT NULL COMMENT '密码',
  `secret_key` varchar(512) DEFAULT NULL COMMENT '秘钥(加密存储)',
  `balance` decimal(36,18) DEFAULT 0 COMMENT '账户总余额(USDT)',
  `country` varchar(32) DEFAULT NULL COMMENT '国家',
  `kyc_level` tinyint unsigned DEFAULT 0 COMMENT 'KYC等级(0未认证 1初级 2高级)',
  `kyc_status` varchar(32) DEFAULT NULL COMMENT 'KYC状态: pending/approved/rejected',
  `status` varchar(32) DEFAULT NULL COMMENT '账户状态: active/locked/frozen',
  `invite_code` varchar(32) DEFAULT NULL COMMENT '邀请码',
  `inviter_id` bigint unsigned DEFAULT 0 COMMENT '邀请人ID',
  `last_login_ip` varchar(64) DEFAULT NULL COMMENT '最后登录IP',
  `last_login_time` datetime DEFAULT NULL COMMENT '最后登录时间',
  `google_auth_key` varchar(64) DEFAULT NULL COMMENT '谷歌验证密钥',
  `two_fa_enabled` tinyint unsigned DEFAULT 0 COMMENT '是否开启二次验证',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_username` (`username`),
  UNIQUE KEY `idx_invite_code` (`invite_code`),
  KEY `idx_platform_id` (`platform_id`),
  KEY `idx_platform_code` (`platform_code`),
  KEY `idx_account` (`account`),
  KEY `idx_email` (`email`),
  KEY `idx_phone` (`phone`),
  KEY `idx_kyc_status` (`kyc_status`),
  KEY `idx_status` (`status`),
  KEY `idx_inviter_id` (`inviter_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='币用户';

CREATE TABLE IF NOT EXISTS `coin_user_asset` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `user_id` bigint unsigned DEFAULT NULL COMMENT '用户ID',
  `coin_id` bigint unsigned DEFAULT NULL COMMENT '币种ID',
  `coin_code` varchar(32) DEFAULT NULL COMMENT '币种代码',
  `available` decimal(36,18) DEFAULT 0 COMMENT '可用余额',
  `frozen` decimal(36,18) DEFAULT 0 COMMENT '冻结余额',
  `total` decimal(36,18) DEFAULT 0 COMMENT '总余额',
  `address` varchar(128) DEFAULT NULL COMMENT '充值地址',
  `withdraw_enable` tinyint unsigned DEFAULT 1 COMMENT '是否允许提现',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_user_coin` (`user_id`, `coin_id`),
  KEY `idx_coin_code` (`coin_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='币用户资产';

CREATE TABLE IF NOT EXISTS `coin_user_login_record` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `user_id` bigint unsigned DEFAULT NULL COMMENT '用户ID',
  `ip` varchar(64) DEFAULT NULL COMMENT '登录IP',
  `device` varchar(128) DEFAULT NULL COMMENT '设备信息',
  `location` varchar(128) DEFAULT NULL COMMENT '位置',
  `success` tinyint unsigned DEFAULT 1 COMMENT '是否成功',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='币用户登录记录';

CREATE TABLE IF NOT EXISTS `coin_user_position` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `user_id` bigint unsigned DEFAULT NULL COMMENT '用户ID',
  `symbol` varchar(32) DEFAULT NULL COMMENT '交易对 BTC-USDT',
  `base_coin_code` varchar(32) DEFAULT NULL COMMENT '基础币种',
  `quote_coin_code` varchar(32) DEFAULT NULL COMMENT '计价币种',
  `amount` decimal(36,18) DEFAULT 0 COMMENT '持仓数量',
  `avg_cost_price` decimal(36,18) DEFAULT 0 COMMENT '平均成本价',
  `total_cost` decimal(36,18) DEFAULT 0 COMMENT '持仓总成本',
  `status` varchar(16) DEFAULT 'open' COMMENT '状态 open/closed',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_user_symbol` (`user_id`, `symbol`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_symbol` (`symbol`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='币用户持仓';

CREATE TABLE IF NOT EXISTS `coin_user_position_analysis` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `user_id` bigint unsigned DEFAULT NULL COMMENT '用户ID',
  `position_id` bigint unsigned DEFAULT 0 COMMENT '关联仓位ID',
  `symbol` varchar(32) DEFAULT NULL COMMENT '币种/交易对 BTC-USDT',
  `side` varchar(8) DEFAULT NULL COMMENT '开仓方向 long/short',
  `avg_price` decimal(36,18) DEFAULT 0 COMMENT '仓位平均价格',
  `liquidation_price` decimal(36,18) DEFAULT 0 COMMENT '爆仓价格',
  `leverage` decimal(10,2) DEFAULT 1 COMMENT '开仓倍数',
  `contracts` decimal(36,18) DEFAULT 0 COMMENT '开仓张数',
  `margin` decimal(36,18) DEFAULT 0 COMMENT '保证金',
  `balance_at_open` decimal(36,18) DEFAULT 0 COMMENT '开仓时用户余额',
  `ai_advice` text COMMENT 'AI建议',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_position_id` (`position_id`),
  KEY `idx_symbol` (`symbol`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='币用户持仓分析';

CREATE TABLE IF NOT EXISTS `trade_order` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `platform_id` bigint unsigned DEFAULT 0 COMMENT '所属平台ID',
  `platform_code` varchar(32) DEFAULT NULL COMMENT '所属平台代码',
  `trade_category` varchar(32) DEFAULT NULL COMMENT '交易类别 spot/futures/margin',
  `trade_type` varchar(16) DEFAULT NULL COMMENT '交易类型 simulation/real',
  `order_no` varchar(64) DEFAULT NULL COMMENT '订单号',
  `user_id` bigint unsigned DEFAULT NULL COMMENT '用户ID',
  `symbol` varchar(32) DEFAULT NULL COMMENT '交易对 BTC-USDT',
  `base_coin_code` varchar(32) DEFAULT NULL COMMENT '基础币种',
  `quote_coin_code` varchar(32) DEFAULT NULL COMMENT '计价币种',
  `side` varchar(8) DEFAULT NULL COMMENT '方向 buy/sell',
  `order_type` varchar(16) DEFAULT NULL COMMENT '类型 limit/market/stop_limit',
  `price` decimal(36,18) DEFAULT 0 COMMENT '委托价格',
  `amount` decimal(36,18) DEFAULT 0 COMMENT '委托数量',
  `total` decimal(36,18) DEFAULT 0 COMMENT '委托总额',
  `stop_price` decimal(36,18) DEFAULT 0 COMMENT '触发价',
  `filled_amount` decimal(36,18) DEFAULT 0 COMMENT '已成交数量',
  `filled_total` decimal(36,18) DEFAULT 0 COMMENT '已成交总额',
  `avg_filled_price` decimal(36,18) DEFAULT 0 COMMENT '平均成交价',
  `fee_coin_code` varchar(32) DEFAULT NULL COMMENT '手续费币种',
  `fee_amount` decimal(36,18) DEFAULT 0 COMMENT '手续费',
  `status` varchar(32) DEFAULT NULL COMMENT '状态 pending/partial/filled/canceled/rejected',
  `time_in_force` varchar(8) DEFAULT 'GTC' COMMENT 'GTC/IOC/FOK',
  `source` varchar(32) DEFAULT NULL COMMENT '下单来源 web/app/api',
  `client_order_id` varchar(64) DEFAULT NULL COMMENT '客户端自定义订单ID',
  `submitted_time` datetime DEFAULT NULL COMMENT '提交时间',
  `finished_time` datetime DEFAULT NULL COMMENT '完结时间',
  `cancel_reason` varchar(255) DEFAULT NULL COMMENT '取消原因',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_order_no` (`order_no`),
  KEY `idx_platform_id` (`platform_id`),
  KEY `idx_platform_code` (`platform_code`),
  KEY `idx_trade_category` (`trade_category`),
  KEY `idx_trade_type` (`trade_type`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_symbol` (`symbol`),
  KEY `idx_side` (`side`),
  KEY `idx_order_type` (`order_type`),
  KEY `idx_status` (`status`),
  KEY `idx_client_order_id` (`client_order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='交易订单';

CREATE TABLE IF NOT EXISTS `trade_match` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `platform_id` bigint unsigned DEFAULT 0 COMMENT '所属平台ID',
  `platform_code` varchar(32) DEFAULT NULL COMMENT '所属平台代码',
  `trade_no` varchar(64) DEFAULT NULL COMMENT '成交单号',
  `symbol` varchar(32) DEFAULT NULL COMMENT '交易对',
  `taker_order_no` varchar(64) DEFAULT NULL COMMENT '吃单订单号',
  `maker_order_no` varchar(64) DEFAULT NULL COMMENT '挂单订单号',
  `taker_user_id` bigint unsigned DEFAULT NULL COMMENT '吃单用户ID',
  `maker_user_id` bigint unsigned DEFAULT NULL COMMENT '挂单用户ID',
  `side` varchar(8) DEFAULT NULL COMMENT '吃单方向 buy/sell',
  `price` decimal(36,18) DEFAULT 0 COMMENT '成交价',
  `amount` decimal(36,18) DEFAULT 0 COMMENT '成交数量',
  `total` decimal(36,18) DEFAULT 0 COMMENT '成交金额',
  `taker_fee` decimal(36,18) DEFAULT 0 COMMENT '吃单手续费',
  `maker_fee` decimal(36,18) DEFAULT 0 COMMENT '挂单手续费',
  `matched_time` datetime DEFAULT NULL COMMENT '撮合时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_trade_no` (`trade_no`),
  KEY `idx_platform_id` (`platform_id`),
  KEY `idx_platform_code` (`platform_code`),
  KEY `idx_symbol` (`symbol`),
  KEY `idx_taker_order_no` (`taker_order_no`),
  KEY `idx_maker_order_no` (`maker_order_no`),
  KEY `idx_taker_user_id` (`taker_user_id`),
  KEY `idx_maker_user_id` (`maker_user_id`),
  KEY `idx_matched_time` (`matched_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='交易成交';

CREATE TABLE IF NOT EXISTS `trade_kline` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `platform_code` varchar(32) NOT NULL DEFAULT 'binance' COMMENT '行情平台代码 binance/deepcoin',
  `symbol` varchar(32) DEFAULT NULL COMMENT '交易对',
  `interval` varchar(8) DEFAULT NULL COMMENT '周期 1m/5m/15m/1h/4h/1d',
  `open_time` datetime DEFAULT NULL COMMENT '开始时间',
  `close_time` datetime DEFAULT NULL COMMENT '结束时间',
  `open_price` decimal(36,18) DEFAULT 0 COMMENT '开盘价',
  `high_price` decimal(36,18) DEFAULT 0 COMMENT '最高价',
  `low_price` decimal(36,18) DEFAULT 0 COMMENT '最低价',
  `close_price` decimal(36,18) DEFAULT 0 COMMENT '收盘价',
  `volume` decimal(36,18) DEFAULT 0 COMMENT '成交量',
  `turnover` decimal(36,18) DEFAULT 0 COMMENT '成交额',
  `trade_count` bigint unsigned DEFAULT 0 COMMENT '成交笔数',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_kline_platform_dim` (`platform_code`, `symbol`, `interval`, `open_time`),
  KEY `idx_platform_code` (`platform_code`),
  KEY `idx_symbol` (`symbol`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='交易K线';

CREATE TABLE IF NOT EXISTS `trade_detail` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `platform_id` bigint unsigned DEFAULT 0 COMMENT '平台ID',
  `platform_code` varchar(32) DEFAULT NULL COMMENT '平台代码',
  `trade_category` varchar(32) DEFAULT NULL COMMENT '交易类别 spot/futures/margin',
  `trade_type` varchar(16) DEFAULT NULL COMMENT '交易类型 simulation/real',
  `user_id` bigint unsigned DEFAULT NULL COMMENT '用户ID',
  `order_no` varchar(64) DEFAULT NULL COMMENT '关联订单号',
  `trade_no` varchar(64) DEFAULT NULL COMMENT '成交单号',
  `symbol` varchar(32) DEFAULT NULL COMMENT '交易对',
  `coin_code` varchar(32) DEFAULT NULL COMMENT '基础币种',
  `side` varchar(8) DEFAULT NULL COMMENT '成交方向 buy/sell',
  `open_direction` varchar(8) DEFAULT NULL COMMENT '开仓方向 long/short',
  `avg_open_price` decimal(36,18) DEFAULT 0 COMMENT '开仓平均价格',
  `liquidation_price` decimal(36,18) DEFAULT 0 COMMENT '爆仓价格',
  `leverage` decimal(10,2) DEFAULT 1 COMMENT '开仓倍数(杠杆)',
  `margin` decimal(36,18) DEFAULT 0 COMMENT '保证金',
  `user_balance_open` decimal(36,18) DEFAULT 0 COMMENT '开仓时用户余额',
  `price` decimal(36,18) DEFAULT 0 COMMENT '成交价',
  `amount` decimal(36,18) DEFAULT 0 COMMENT '成交数量',
  `total` decimal(36,18) DEFAULT 0 COMMENT '成交金额',
  `fee` decimal(36,18) DEFAULT 0 COMMENT '手续费',
  `pnl` decimal(36,18) DEFAULT 0 COMMENT '盈亏金额',
  `pnl_rate` decimal(18,8) DEFAULT 0 COMMENT '盈亏比率',
  `trade_time` datetime DEFAULT NULL COMMENT '成交时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_trade_no` (`trade_no`),
  KEY `idx_platform_id` (`platform_id`),
  KEY `idx_platform_code` (`platform_code`),
  KEY `idx_trade_category` (`trade_category`),
  KEY `idx_trade_type` (`trade_type`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_order_no` (`order_no`),
  KEY `idx_symbol` (`symbol`),
  KEY `idx_coin_code` (`coin_code`),
  KEY `idx_open_direction` (`open_direction`),
  KEY `idx_trade_time` (`trade_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='交易明细盈亏';

CREATE TABLE IF NOT EXISTS `trade_user_summary` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `user_id` bigint unsigned DEFAULT NULL COMMENT '用户ID',
  `platform_id` bigint unsigned DEFAULT NULL COMMENT '平台ID',
  `platform_code` varchar(32) DEFAULT NULL COMMENT '平台代码',
  `coin_code` varchar(32) DEFAULT NULL COMMENT '币种代码',
  `trade_category` varchar(32) DEFAULT NULL COMMENT '交易类别',
  `trade_date` varchar(10) DEFAULT NULL COMMENT '交易日期 yyyy-MM-dd',
  `total_orders` bigint DEFAULT 0 COMMENT '总订单数',
  `buy_orders` bigint DEFAULT 0 COMMENT '买入订单数',
  `sell_orders` bigint DEFAULT 0 COMMENT '卖出订单数',
  `buy_amount` decimal(36,18) DEFAULT 0 COMMENT '买入数量',
  `sell_amount` decimal(36,18) DEFAULT 0 COMMENT '卖出数量',
  `buy_total` decimal(36,18) DEFAULT 0 COMMENT '买入金额',
  `sell_total` decimal(36,18) DEFAULT 0 COMMENT '卖出金额',
  `total_fee` decimal(36,18) DEFAULT 0 COMMENT '总手续费',
  `total_volume` decimal(36,18) DEFAULT 0 COMMENT '总成交额',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_summary_dim` (`user_id`, `platform_id`, `coin_code`, `trade_category`, `trade_date`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_trade_date` (`trade_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户交易汇总';

CREATE TABLE IF NOT EXISTS `trade_user_pnl` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `user_id` bigint unsigned DEFAULT NULL COMMENT '用户ID',
  `platform_id` bigint unsigned DEFAULT NULL COMMENT '平台ID',
  `platform_code` varchar(32) DEFAULT NULL COMMENT '平台代码',
  `coin_code` varchar(32) DEFAULT NULL COMMENT '币种代码',
  `trade_category` varchar(32) DEFAULT NULL COMMENT '交易类别',
  `trade_date` varchar(10) DEFAULT NULL COMMENT '交易日期 yyyy-MM-dd',
  `realized_pnl` decimal(36,18) DEFAULT 0 COMMENT '已实现盈亏',
  `unrealized_pnl` decimal(36,18) DEFAULT 0 COMMENT '未实现盈亏',
  `total_pnl` decimal(36,18) DEFAULT 0 COMMENT '总盈亏',
  `pnl_rate` decimal(18,8) DEFAULT 0 COMMENT '盈亏比率',
  `position_amount` decimal(36,18) DEFAULT 0 COMMENT '持仓数量',
  `position_cost` decimal(36,18) DEFAULT 0 COMMENT '持仓成本',
  `position_value` decimal(36,18) DEFAULT 0 COMMENT '持仓市值',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_pnl_dim` (`user_id`, `platform_id`, `coin_code`, `trade_category`, `trade_date`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_trade_date` (`trade_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户交易盈亏';

-- ===========================================================================
-- req-1788169552180 套利策略可视化管理端重构 · 新增 10 张表
--
-- 这些表在运行时由代码里的 EnsureTable() / GORM AutoMigrate 自动建立，
-- 本段是与实体定义对齐的可读快照，供查表结构与人工建库用，不是迁移入口：
--   · argus_instance                      -> ArgusConfigRepository.EnsureTable
--   · trade_backtest_batch / trade_optimize_study / trade_optimize_cell
--                                          -> TradeService.EnsureTable
--   · strategy_event / balance_sample / dev_sample / signal_slice
--                                          -> argus_single/pkg/eventstore.Setup
--   · episode / episode_entry              -> argus_single/pkg/eventstore/episode
--
-- 生成方式：用 gorm.io/gorm/schema 解析同一批实体的 tag，故与 AutoMigrate
-- 实际建出的表一致。实体改了请重新生成，不要手改本段。
-- 例外：argus_instance 的 chk_argus_instance_enabled 是照 gorm 的 check: tag
-- 手工补的（schema 解析不吐 CHECK），重新生成时记得带上。本段其余 9 张表无 CHECK。
--
-- 注意两处 AutoMigrate 管不了、已在代码里显式处理的结构迁移（本段不含）：
--   · trade_kline 旧唯一索引 idx_symbol_interval_open 需 DROP，
--     见 service/trade/repository/repository.go migrateKlinePlatformDim
--   · argus_config_version 的两个唯一索引需重建为实例内唯一，
--     见 service/argus_config/repository/repository.go EnsureInstanceScopedIndexes
-- ===========================================================================

CREATE TABLE IF NOT EXISTS `argus_instance` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `instance_key` varchar(64) DEFAULT NULL COMMENT '实例唯一键，对应 argus.instance.id',
  `instance_name` varchar(128) DEFAULT NULL COMMENT '实例展示名',
  `description` varchar(500) DEFAULT NULL COMMENT '实例说明',
  `config_source` varchar(255) DEFAULT NULL COMMENT '导入来源的 properties 文件名',
  `enabled` tinyint unsigned DEFAULT 1 COMMENT '实例启用状态',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_argus_instance_key` (`instance_key`),
  CONSTRAINT `chk_argus_instance_enabled` CHECK (`enabled` IN (0,1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Argus 实例注册表';

CREATE TABLE IF NOT EXISTS `trade_backtest_batch` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `name` varchar(128) DEFAULT NULL COMMENT '批次名',
  `instance_key` varchar(64) DEFAULT NULL COMMENT '信号源实例键',
  `account_label` varchar(128) DEFAULT NULL COMMENT '信号源账户',
  `platform_code` varchar(32) DEFAULT NULL COMMENT '1m 路径回放平台',
  `symbol` varchar(32) DEFAULT NULL COMMENT '交易对',
  `coin_code` varchar(32) DEFAULT NULL COMMENT '基础币种',
  `start_time` datetime DEFAULT NULL COMMENT '扫描窗口起',
  `end_time` datetime DEFAULT NULL COMMENT '扫描窗口止',
  `baseline_snapshot` text DEFAULT NULL COMMENT '基线参数冻结快照(JSON)',
  `baseline_source` varchar(32) DEFAULT NULL COMMENT '基线来源 instance_published/request',
  `baseline_note` varchar(1024) DEFAULT NULL COMMENT '基线取值来源与兜底说明',
  `baseline_run_id` bigint DEFAULT 0 COMMENT '基线组对应的 run_id，0=未跑基线',
  `concurrency` int DEFAULT 1 COMMENT '并发执行的组数上限',
  `group_count` int DEFAULT 0 COMMENT '本批次的参数组数(含基线组)',
  `done_count` int DEFAULT 0 COMMENT '已完成组数',
  `failed_count` int DEFAULT 0 COMMENT '失败组数',
  `status` varchar(16) DEFAULT 'pending' COMMENT '状态 pending/running/done/partial/failed',
  `error_msg` varchar(512) DEFAULT NULL COMMENT '批次级失败原因(取数失败等)',
  PRIMARY KEY (`id`),
  KEY `idx_bt_batch_inst` (`instance_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='盘口信号回测批次';

CREATE TABLE IF NOT EXISTS `trade_optimize_study` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `name` varchar(128) DEFAULT NULL COMMENT '扫描任务名',
  `instance_key` varchar(64) DEFAULT NULL COMMENT '信号源实例键',
  `account_label` varchar(128) DEFAULT NULL COMMENT '信号源账户',
  `platform_code` varchar(32) DEFAULT NULL COMMENT '1m 路径回放平台',
  `symbol` varchar(32) DEFAULT NULL COMMENT '交易对',
  `coin_code` varchar(32) DEFAULT NULL COMMENT '基础币种',
  `start_time` datetime DEFAULT NULL COMMENT '扫描窗口起',
  `end_time` datetime DEFAULT NULL COMMENT '扫描窗口止',
  `sample_kind` varchar(16) DEFAULT 'in_sample' COMMENT '样本口径 in_sample/out_of_sample',
  `sample_note` varchar(512) DEFAULT NULL COMMENT '样本口径说明',
  `oos_base_id` bigint DEFAULT 0 COMMENT 'out_of_sample 任务继承的基准扫描 id，0=无',
  `space_snapshot` text DEFAULT NULL COMMENT '搜索空间快照(JSON signal.SearchSpace)',
  `protocol_snapshot` text DEFAULT NULL COMMENT '降噪协议快照(JSON signal.Protocol)',
  `converge_snapshot` text DEFAULT NULL COMMENT '粗→精收敛规则快照(JSON signal.Convergence)',
  `gate_snapshot` text DEFAULT NULL COMMENT '预注册三关阈值快照(JSON signal.Gates)',
  `gate_locked_at` datetime DEFAULT NULL COMMENT '阈值锁定时刻(发起时写死，跑完不可改)',
  `gate_note` varchar(512) DEFAULT NULL COMMENT '三关阈值的可读表述',
  `baseline_snapshot` text DEFAULT NULL COMMENT '基线参数冻结快照(JSON signal.Params)',
  `baseline_source` varchar(32) DEFAULT NULL COMMENT '基线来源 instance_published/request',
  `baseline_note` varchar(1024) DEFAULT NULL COMMENT '基线取值来源与兜底说明',
  `incumbent_snapshot` varchar(512) DEFAULT NULL COMMENT '现行配置格快照(JSON signal.CellSpec)，空=未解析出',
  `stage` varchar(16) DEFAULT 'coarse' COMMENT '阶段 coarse/fine/concluded',
  `concurrency` int DEFAULT 1 COMMENT '并发执行的格数上限',
  `coarse_cell_count` int DEFAULT 0 COMMENT '粗网格格数',
  `fine_cell_count` int DEFAULT 0 COMMENT '精算格数',
  `done_cell_count` int DEFAULT 0 COMMENT '已完成格数',
  `failed_cell_count` int DEFAULT 0 COMMENT '失败格数',
  `skip_cell_count` int DEFAULT 0 COMMENT '参数非法被跳过的格数',
  `replay_count` int DEFAULT 0 COMMENT '累计回放次数(格数×路径数)',
  `status` varchar(16) DEFAULT 'pending' COMMENT '状态 pending/running/done/partial/failed',
  `error_msg` varchar(512) DEFAULT NULL COMMENT '任务级失败原因',
  `converge_note` varchar(1024) DEFAULT NULL COMMENT '精算格是怎么从粗网格收敛出来的',
  `signal_count` int DEFAULT 0 COMMENT '窗口内真实触发数',
  `kline_count` int DEFAULT 0 COMMENT '窗口内 1m 根数',
  `trend_day_count` int DEFAULT 0 COMMENT '窗口内单边日天数(熊市月情景的样本基数)',
  `vol_day_count` int DEFAULT 0 COMMENT '窗口内震荡日天数',
  `verdict` varchar(24) DEFAULT NULL COMMENT '结论 candidate_found/no_solution，空=未出结论',
  `passed_cell_count` int DEFAULT 0 COMMENT '通过三关的格数',
  `conclusion` text DEFAULT NULL COMMENT '结论正文(JSON signal.Conclusion)',
  `frontier_snapshot` text DEFAULT NULL COMMENT '权衡前沿快照(JSON []signal.FrontierPoint)',
  `scale_snapshot` text DEFAULT NULL COMMENT '规模不变性核查快照(JSON []signal.ScaleInvarianceCheck)',
  PRIMARY KEY (`id`),
  KEY `idx_opt_study_inst` (`instance_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='自动参数寻优任务';

CREATE TABLE IF NOT EXISTS `trade_optimize_cell` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `active` tinyint DEFAULT 1 COMMENT '记录是否有效(1有效，0无效)，逻辑删除标识',
  `created_time` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_time` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `updated_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `study_id` bigint NOT NULL COMMENT '关联寻优任务ID',
  `stage` varchar(16) DEFAULT NULL COMMENT '阶段 coarse/fine',
  `cell_key` varchar(64) DEFAULT NULL COMMENT '格子标识 如 net(26,400,g20)',
  `mode` varchar(8) DEFAULT NULL COMMENT '持仓形态 net/dual',
  `cap_contracts` int DEFAULT 0 COMMENT '仓位上限张数(dual 为每侧上限)；999=∞对照',
  `stop_pct` decimal(18,6) DEFAULT 0 COMMENT 'S 兜底止损 ROI%',
  `gate_pct` decimal(18,6) DEFAULT 0 COMMENT '反向门控最低盈利%',
  `params_snapshot` text DEFAULT NULL COMMENT '本格完整参数快照(JSON signal.Params)',
  `fidelity` varchar(16) DEFAULT 'event' COMMENT '精度等级；寻优只做事件级',
  `status` varchar(16) DEFAULT 'pending' COMMENT '状态 pending/running/done/failed/skipped',
  `error_msg` varchar(512) DEFAULT NULL COMMENT '失败或跳过原因',
  `path_count` int DEFAULT 0 COMMENT '实际跑通的抖动路径数',
  `med_pnl28` decimal(24,8) DEFAULT 0 COMMENT '中位净利(归一到 28 天)',
  `p25_pnl28` decimal(24,8) DEFAULT 0 COMMENT '净利 p25',
  `p75_pnl28` decimal(24,8) DEFAULT 0 COMMENT '净利 p75',
  `iqr_pnl28` decimal(24,8) DEFAULT 0 COMMENT '净利 IQR',
  `min_pnl28` decimal(24,8) DEFAULT 0 COMMENT '净利最小值',
  `max_pnl28` decimal(24,8) DEFAULT 0 COMMENT '净利最大值',
  `sign_ratio` decimal(18,6) DEFAULT 0 COMMENT '符号一致率(pnl>0 的路径占比)',
  `lambda_bear` decimal(18,6) DEFAULT 0 COMMENT '单边日口径兜底频率 次/月',
  `mean_stop_loss` decimal(24,8) DEFAULT 0 COMMENT '单次兜底平均损失额',
  `stop_budget` decimal(24,8) DEFAULT 0 COMMENT '月度兜底预算消耗 λ×损失',
  `stop_count` int DEFAULT 0 COMMENT '全路径兜底总次数',
  `p90_max_drawdown` decimal(24,8) DEFAULT 0 COMMENT 'p90 MTM 最大回撤',
  `max_stack` int DEFAULT 0 COMMENT '最大堆积张数',
  `med_fee` decimal(24,8) DEFAULT 0 COMMENT '中位手续费',
  `med_days` decimal(18,6) DEFAULT 0 COMMENT '中位覆盖天数',
  `med_signal_run` int DEFAULT 0 COMMENT '中位回放触发数',
  `bear_pool_size` int DEFAULT 0 COMMENT '熊市月重采样池大小',
  `bear_p10` decimal(24,8) DEFAULT 0 COMMENT '熊市月净 p10',
  `bear_p50` decimal(24,8) DEFAULT 0 COMMENT '熊市月净 p50',
  `bear_p90` decimal(24,8) DEFAULT 0 COMMENT '熊市月净 p90',
  `chop_p10` decimal(24,8) DEFAULT 0 COMMENT '震荡月净 p10',
  `chop_p50` decimal(24,8) DEFAULT 0 COMMENT '震荡月净 p50',
  `mixed_p10` decimal(24,8) DEFAULT 0 COMMENT '混合月净 p10',
  `mixed_p50` decimal(24,8) DEFAULT 0 COMMENT '混合月净 p50',
  `ok_sign` tinyint DEFAULT 0 COMMENT '符号一致率关 1=过',
  `ok_bear` tinyint DEFAULT 0 COMMENT '熊市月净 p10 关 1=过',
  `ok_dd` tinyint DEFAULT 0 COMMENT 'p90 回撤关 1=过',
  `ok_budget` tinyint DEFAULT 0 COMMENT '参考项：频率预算 1=过(不计入三关)',
  `passed` tinyint DEFAULT 0 COMMENT '三关全过 1=候选',
  `pass_count` int DEFAULT 0 COMMENT '通过的关数 0-3',
  `verdict_note` varchar(1024) DEFAULT NULL COMMENT '未过关的逐条原因',
  `dominated_by` varchar(512) DEFAULT NULL COMMENT '全面支配本格的格子键，逗号分隔',
  `is_incumbent` tinyint DEFAULT 0 COMMENT '1=现行线上配置对应的格',
  `on_dd_frontier` tinyint DEFAULT 0 COMMENT '1=在收益/回撤前沿上',
  `on_bear_frontier` tinyint DEFAULT 0 COMMENT '1=在收益/熊市尾部前沿上',
  `paths_snapshot` text DEFAULT NULL COMMENT '逐路径产出快照(JSON []signal.PathOutcome)',
  `note_snapshot` text DEFAULT NULL COMMENT '本格必须随结果展示的口径说明(JSON []string)',
  PRIMARY KEY (`id`),
  KEY `idx_opt_cell_study` (`study_id`, `stage`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='自动参数寻优参数格';

CREATE TABLE IF NOT EXISTS `strategy_event` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `event_hash` binary(16) NOT NULL COMMENT 'Go 侧算的幂等哈希，见 hash.go',
  `ts` datetime NOT NULL COMMENT '事件时刻，本地时区口径，与 JSONL 逐字一致',
  `instance_key` varchar(64) NOT NULL COMMENT '实例键，对应 argus_instance.instance_key',
  `config_version` bigint unsigned NOT NULL DEFAULT 0 COMMENT '事件发生时该实例生效的配置版本号',
  `uid` varchar(32) NOT NULL DEFAULT '' COMMENT '数字 uid；配置未填时为空，账户唯一性回退 (instance_key, account_label)',
  `account_label` varchar(128) NOT NULL DEFAULT '' COMMENT 'JSONL 原 account 串（含邮箱标签）',
  `variant` varchar(64) DEFAULT NULL COMMENT '策略变体标签，自由文本、会持续新增',
  `event` varchar(24) NOT NULL COMMENT '事件类型',
  `instrument` varchar(24) NOT NULL DEFAULT '' COMMENT '归一化合约（BTCUSDT）',
  `inst_id_raw` varchar(32) DEFAULT NULL COMMENT 'JSONL 原 instId，对账用',
  `side` varchar(8) DEFAULT NULL COMMENT '本次动作方向',
  `net_side` varchar(8) DEFAULT NULL COMMENT '净仓方向',
  `size` int DEFAULT NULL COMMENT '结果净仓张数（open）或持仓张数（平仓类）',
  `order_size` int DEFAULT NULL COMMENT '本次下单张数',
  `avg_px` decimal(20,8) DEFAULT NULL COMMENT '开仓均价',
  `last_px` decimal(20,8) DEFAULT NULL COMMENT '最新价',
  `roi_pct` decimal(14,6) DEFAULT NULL COMMENT 'ROI%（含杠杆口径）',
  `pnl` decimal(20,8) DEFAULT NULL COMMENT '盈亏',
  `peak_pct` decimal(14,6) DEFAULT NULL COMMENT '平仓时 trail 峰值（激活过才有）',
  `sig_last` decimal(20,8) DEFAULT NULL COMMENT '信号时刻 DeepCoin last',
  `sig_mark` decimal(20,8) DEFAULT NULL COMMENT '信号时刻 mark',
  `gap_bp` decimal(12,4) DEFAULT NULL COMMENT '偏离 bp，带符号（>0=UP）',
  `trend_mom_pct` decimal(14,6) DEFAULT NULL COMMENT '趋势闸拦截时刻的窗口动量%',
  `gate_kind` varchar(32) DEFAULT NULL COMMENT '门控种类，见 gate.go；非拦截事件为 NULL',
  `gate_threshold` decimal(20,8) DEFAULT NULL COMMENT '门控阈值（结构化自 reason）',
  `gate_actual` decimal(20,8) DEFAULT NULL COMMENT '门控实际值（结构化自 reason）',
  `reason` varchar(255) DEFAULT NULL COMMENT '原始 reason 文本，保留以便与 TG 消息逐字对账',
  `source` tinyint NOT NULL COMMENT '1=直写 2=回灌',
  `ext` json DEFAULT NULL COMMENT '将来新字段落这里，不改表',
  `ingested_at` datetime(3) NOT NULL COMMENT '入库时刻',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_strategy_event_hash` (`event_hash`),
  KEY `idx_strategy_event_gate` (`gate_kind`, `ts`),
  KEY `idx_strategy_event_inst_event_ts` (`instance_key`, `event`, `ts`),
  KEY `idx_strategy_event_inst_ts` (`instance_key`, `ts`),
  KEY `idx_strategy_event_ts` (`ts`),
  KEY `idx_strategy_event_uid_ts` (`instance_key`, `uid`, `ts`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='策略稀疏业务事件（append-only 事实表）';

CREATE TABLE IF NOT EXISTS `balance_sample` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `event_hash` binary(16) NOT NULL COMMENT '幂等哈希',
  `ts` datetime NOT NULL COMMENT '采样时刻',
  `instance_key` varchar(64) NOT NULL COMMENT '实例键',
  `config_version` bigint unsigned NOT NULL DEFAULT 0 COMMENT '生效配置版本号',
  `uid` varchar(32) NOT NULL DEFAULT '' COMMENT '数字 uid',
  `account_label` varchar(128) NOT NULL DEFAULT '' COMMENT 'JSONL 原 account 串',
  `variant` varchar(64) DEFAULT NULL COMMENT '策略变体标签',
  `balance` decimal(20,8) NOT NULL COMMENT 'USDT 余额',
  `equity` decimal(20,8) DEFAULT NULL COMMENT 'balance+UPL；NULL=该口径不可用',
  `upl` decimal(20,8) DEFAULT NULL COMMENT '未实现盈亏合计',
  `equity_known` tinyint unsigned NOT NULL DEFAULT 0 COMMENT 'equity 已知性；0/负权益也是已知样本',
  `net_size` int DEFAULT NULL COMMENT '净仓张数快照',
  `net_size_known` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '区分『已知空仓』与『字段未上线』',
  `source` tinyint NOT NULL COMMENT '1=直写 2=回灌',
  `ingested_at` datetime(3) NOT NULL COMMENT '入库时刻',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_balance_sample_hash` (`event_hash`),
  KEY `idx_balance_sample_inst_uid_ts` (`instance_key`, `uid`, `ts`),
  KEY `idx_balance_sample_ts` (`ts`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='分钟级余额/权益心跳（append-only 事实表）';

CREATE TABLE IF NOT EXISTS `dev_sample` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `event_hash` binary(16) NOT NULL COMMENT '幂等哈希',
  `ts` datetime NOT NULL COMMENT '窗口落盘时刻',
  `instance_key` varchar(64) NOT NULL COMMENT '实例键',
  `config_version` bigint unsigned NOT NULL DEFAULT 0 COMMENT '生效配置版本号',
  `instrument` varchar(24) NOT NULL DEFAULT '' COMMENT '归一化合约',
  `inst_id_raw` varchar(32) DEFAULT NULL COMMENT 'JSONL 原 instId',
  `dev_ticks` int NOT NULL COMMENT '窗口内有效 tick 数；非零即表示采样器在工作',
  `dev_max_bp` decimal(12,4) DEFAULT NULL COMMENT '窗口内 |dev| 极值',
  `dev_mean_bp` decimal(12,4) DEFAULT NULL COMMENT '窗口内 |dev| 均值',
  `dev_cross_json` json DEFAULT NULL COMMENT '各候选阈值(bp)的穿越次数 → λ(θ)',
  `dev_over_json` json DEFAULT NULL COMMENT '各候选阈值(bp)的超阈 tick 数 → P(|dev|>θ)',
  `source` tinyint NOT NULL COMMENT '1=直写 2=回灌',
  `ingested_at` datetime(3) NOT NULL COMMENT '入库时刻',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dev_sample_hash` (`event_hash`),
  KEY `idx_dev_sample_inst_ts` (`instance_key`, `instrument`, `ts`),
  KEY `idx_dev_sample_ts` (`ts`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='无条件偏离采样（append-only 事实表）';

CREATE TABLE IF NOT EXISTS `signal_slice` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ts` datetime NOT NULL COMMENT '触发时刻（锚点），与 strategy_event.ts 同口径',
  `instance_key` varchar(64) NOT NULL COMMENT '实例键，对应 argus_instance.instance_key',
  `config_version` bigint unsigned NOT NULL DEFAULT 0 COMMENT '生效配置版本号',
  `instrument` varchar(24) NOT NULL DEFAULT '' COMMENT '归一化合约（BTCUSDT）',
  `inst_id_raw` varchar(32) DEFAULT NULL COMMENT '原始 instId，对账用',
  `start_at` datetime NOT NULL COMMENT '窗口左界 = ts - half_window_sec',
  `end_at` datetime NOT NULL COMMENT '窗口右界 = ts + half_window_sec',
  `half_window_sec` smallint NOT NULL COMMENT '半窗秒数（当前恒为 60）',
  `series_points` smallint NOT NULL COMMENT '每条序列的点数（2*half+1，当前 121）',
  `dc_points` smallint NOT NULL DEFAULT 0 COMMENT 'DC 序列非空点数；覆盖率，判断切片是否可用',
  `bin_points` smallint NOT NULL DEFAULT 0 COMMENT '币安序列非空点数',
  `dc_last_json` json NOT NULL COMMENT 'DeepCoin last 逐秒序列，null 元素=该秒无 tick（不插值）',
  `dc_mark_json` json NOT NULL COMMENT 'DeepCoin mark 逐秒序列',
  `bin_last_json` json NOT NULL COMMENT '币安 last 逐秒序列',
  `source` tinyint NOT NULL COMMENT '1=直写 2=回灌',
  `ingested_at` datetime(3) NOT NULL COMMENT '入库时刻',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_signal_slice_anchor` (`instance_key`, `instrument`, `ts`),
  KEY `idx_signal_slice_ts` (`ts`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='触发瞬间秒级行情切片（90 天滚动派生表）';

CREATE TABLE IF NOT EXISTS `episode` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `instance_key` varchar(64) NOT NULL COMMENT '实例键，对应 argus_instance.instance_key',
  `uid` varchar(32) NOT NULL DEFAULT '' COMMENT '数字 uid；配置未填时为空',
  `account_label` varchar(128) NOT NULL DEFAULT '' COMMENT 'JSONL 原 account 串，账户归属的唯一可靠依据',
  `instrument` varchar(24) NOT NULL DEFAULT '' COMMENT '归一化合约（BTCUSDT）',
  `side` varchar(8) NOT NULL DEFAULT '' COMMENT '该 episode 的持仓方向',
  `first_event_at` datetime NOT NULL COMMENT '本 episode 观测到的首条事件时刻',
  `opened_at` datetime DEFAULT NULL COMMENT '建仓时刻；NULL=开头被数据窗口截断',
  `last_event_at` datetime NOT NULL COMMENT '本 episode 观测到的末条事件时刻；仍持仓时即窗口右端',
  `closed_at` datetime DEFAULT NULL COMMENT '出场时刻；NULL=仍持仓中',
  `duration_sec` int DEFAULT NULL COMMENT '持仓时长秒；opened_at/closed_at 任一为空则为 NULL',
  `exit_kind` varchar(24) DEFAULT NULL COMMENT '六种出场方式之一；NULL=仍持仓',
  `exit_event_hash` binary(16) DEFAULT NULL COMMENT '出场那条 strategy_event 的 event_hash，可回溯原始事件',
  `strategy_attributable` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '是否计入策略胜率',
  `add_count` int NOT NULL DEFAULT 0 COMMENT '加仓（含首仓）决策次数',
  `reduce_count` int NOT NULL DEFAULT 0 COMMENT '反向减仓次数',
  `entry_size_total` int NOT NULL DEFAULT 0 COMMENT '本 episode 累计建仓张数，决策归集的分母',
  `max_size` int NOT NULL DEFAULT 0 COMMENT '峰值净仓张数',
  `open_size` decimal(20,8) NOT NULL DEFAULT 0 COMMENT '重建时点仍在场的张数；已出场则为 0',
  `hidden_size` decimal(20,8) NOT NULL DEFAULT 0 COMMENT '在场但建仓决策不可见的张数',
  `min_roi_pct_observed` decimal(14,6) DEFAULT NULL COMMENT '观测最深 ROI%，是真实值的下界（loss_alert 5 分钟采样）',
  `max_roi_pct_observed` decimal(14,6) DEFAULT NULL COMMENT '观测最高 ROI%，同样只是观测值不是真实极值',
  `peak_pct` decimal(14,6) DEFAULT NULL COMMENT '平仓事件带的 trail 峰值（trail 激活过才有）',
  `exit_roi_pct` decimal(14,6) DEFAULT NULL COMMENT '出场那一刻的 ROI%',
  `pnl` decimal(20,8) NOT NULL DEFAULT 0 COMMENT '本 episode 已知的已实现盈亏合计（含减仓锁利）',
  `pnl_strategy` decimal(20,8) NOT NULL DEFAULT 0 COMMENT '其中由策略自身决定出场的部分（剔除 external/manual）',
  `unattributed_pnl` decimal(20,8) NOT NULL DEFAULT 0 COMMENT '落不到任何建仓决策上的已实现盈亏',
  `realized_events` int NOT NULL DEFAULT 0 COMMENT '带已知盈亏的实现次数',
  `missing_pnl_events` int NOT NULL DEFAULT 0 COMMENT '实现了但盈亏未知的次数；>0 时 pnl 不完整',
  `cap_skip_count` int NOT NULL DEFAULT 0 COMMENT '持仓期内被仓位上限挡掉的信号数',
  `gate_block_count` int NOT NULL DEFAULT 0 COMMENT '持仓期内被反向门控挡掉的信号数',
  `trend_skip_count` int NOT NULL DEFAULT 0 COMMENT '持仓期内被趋势闸挡掉的信号数',
  `loss_alert_count` int NOT NULL DEFAULT 0 COMMENT '持仓期内的深度告警条数',
  `balance_sample_count` int NOT NULL DEFAULT 0 COMMENT '窗口内的余额心跳总条数',
  `upl_sample_count` int NOT NULL DEFAULT 0 COMMENT '其中带 upl 的条数；两者之比决定 depth_fidelity',
  `position_gap_count` int NOT NULL DEFAULT 0 COMMENT '|Δsize| != orderSize 的次数',
  `has_position_gap` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '仓位跳变标记',
  `variant` varchar(64) DEFAULT NULL COMMENT '开仓时刻的 variant（决策时刻口径）',
  `config_version` bigint unsigned NOT NULL DEFAULT 0 COMMENT '开仓时刻生效的配置版本号',
  `depth_fidelity` varchar(16) NOT NULL DEFAULT '' COMMENT 'minute / alert_sampled / mixed',
  `rebuilt_at` datetime(3) NOT NULL COMMENT '本行的重建时刻',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_episode_anchor` (`instance_key`, `account_label`, `instrument`, `first_event_at`),
  KEY `idx_episode_closed` (`closed_at`),
  KEY `idx_episode_exit` (`exit_kind`),
  KEY `idx_episode_inst_opened` (`instance_key`, `opened_at`),
  KEY `idx_episode_variant` (`variant`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='持仓生命周期 episode（派生表，可整表重建）';

CREATE TABLE IF NOT EXISTS `episode_entry` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `episode_id` bigint unsigned NOT NULL COMMENT '所属 episode',
  `instance_key` varchar(64) NOT NULL COMMENT '实例键',
  `uid` varchar(32) NOT NULL DEFAULT '' COMMENT '数字 uid',
  `account_label` varchar(128) NOT NULL DEFAULT '' COMMENT 'JSONL 原 account 串',
  `instrument` varchar(24) NOT NULL DEFAULT '' COMMENT '归一化合约',
  `side` varchar(8) NOT NULL DEFAULT '' COMMENT '建仓方向（= episode 方向）',
  `decided_at` datetime NOT NULL COMMENT '建仓决策时刻',
  `event_hash` binary(16) NOT NULL COMMENT '对应那条 open 事件的 event_hash，一笔决策一行',
  `added_size` int NOT NULL DEFAULT 0 COMMENT '本次决策加的张数（按仓位快照实算，可能 != orderSize）',
  `order_size` int DEFAULT NULL COMMENT '事件里写的下单张数，与 added_size 不等即仓位跳变',
  `closed_size` decimal(20,8) NOT NULL DEFAULT 0 COMMENT '已退场张数（等比例摊，故为小数）',
  `open_size` decimal(20,8) NOT NULL DEFAULT 0 COMMENT '重建时点仍在场张数',
  `attributed_pnl` decimal(20,8) NOT NULL DEFAULT 0 COMMENT '归给本次决策的已实现盈亏',
  `attributed_pnl_strategy` decimal(20,8) NOT NULL DEFAULT 0 COMMENT '其中剔除 external/manual 出场后的部分',
  `missing_pnl_events` int NOT NULL DEFAULT 0 COMMENT '在场期间盈亏未知的实现次数',
  `pnl_known` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '已完全出场且期间没有未知盈亏；0=归因不完整',
  `variant` varchar(64) DEFAULT NULL COMMENT '决策时刻的 variant',
  `config_version` bigint unsigned NOT NULL DEFAULT 0 COMMENT '决策时刻生效的配置版本号',
  `gap_bp` decimal(12,4) DEFAULT NULL COMMENT '触发本次建仓的偏离 bp（带符号，>0=UP）',
  `avg_px` decimal(20,8) DEFAULT NULL COMMENT '决策时刻的持仓均价',
  `last_px` decimal(20,8) DEFAULT NULL COMMENT '决策时刻的最新价',
  `exit_kind` varchar(24) DEFAULT NULL COMMENT '所属 episode 的出场方式；NULL=仍持仓',
  `strategy_attributable` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '所属 episode 是否计入策略胜率',
  `rebuilt_at` datetime(3) NOT NULL COMMENT '本行的重建时刻',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_episode_entry_event` (`event_hash`),
  KEY `idx_episode_entry_ep` (`episode_id`),
  KEY `idx_episode_entry_inst_decided` (`instance_key`, `decided_at`),
  KEY `idx_episode_entry_variant` (`variant`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='建仓决策与决策归集盈亏（派生表，可整表重建）';

